# Generated by Django 4.0.4 on 2022-05-14 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_flows", "0021_auto_20211227_2103"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtAuthStage",
            fields=[
                (
                    "stage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_flows.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "ExtAuth Stage",
                "verbose_name_plural": "ExtAuth Stages",
            },
            bases=("authentik_flows.stage",),
        ),
    ]
