# Generated by Django 4.0.4 on 2022-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_ext_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extauthstage",
            name="silent",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the HTML flow executor will immediately initiate logging in with the user's external authentication service.",
            ),
        ),
    ]
