# Generated by Django 4.1.7 on 2023-05-16 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_stages_ext_auth", "0002_extauthstage_silent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extauthstage",
            name="silent",
        ),
    ]
