/*
authentik

Making authentication simple.

API version: 2024.2.1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SystemInfoRuntime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInfoRuntime{}

// SystemInfoRuntime Get versions
type SystemInfoRuntime struct {
	PythonVersion string `json:"python_version"`
	GunicornVersion string `json:"gunicorn_version"`
	Environment string `json:"environment"`
	Architecture string `json:"architecture"`
	Platform string `json:"platform"`
	Uname string `json:"uname"`
}

// NewSystemInfoRuntime instantiates a new SystemInfoRuntime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInfoRuntime(pythonVersion string, gunicornVersion string, environment string, architecture string, platform string, uname string) *SystemInfoRuntime {
	this := SystemInfoRuntime{}
	this.PythonVersion = pythonVersion
	this.GunicornVersion = gunicornVersion
	this.Environment = environment
	this.Architecture = architecture
	this.Platform = platform
	this.Uname = uname
	return &this
}

// NewSystemInfoRuntimeWithDefaults instantiates a new SystemInfoRuntime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInfoRuntimeWithDefaults() *SystemInfoRuntime {
	this := SystemInfoRuntime{}
	return &this
}

// GetPythonVersion returns the PythonVersion field value
func (o *SystemInfoRuntime) GetPythonVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PythonVersion
}

// GetPythonVersionOk returns a tuple with the PythonVersion field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetPythonVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PythonVersion, true
}

// SetPythonVersion sets field value
func (o *SystemInfoRuntime) SetPythonVersion(v string) {
	o.PythonVersion = v
}

// GetGunicornVersion returns the GunicornVersion field value
func (o *SystemInfoRuntime) GetGunicornVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GunicornVersion
}

// GetGunicornVersionOk returns a tuple with the GunicornVersion field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetGunicornVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GunicornVersion, true
}

// SetGunicornVersion sets field value
func (o *SystemInfoRuntime) SetGunicornVersion(v string) {
	o.GunicornVersion = v
}

// GetEnvironment returns the Environment field value
func (o *SystemInfoRuntime) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *SystemInfoRuntime) SetEnvironment(v string) {
	o.Environment = v
}

// GetArchitecture returns the Architecture field value
func (o *SystemInfoRuntime) GetArchitecture() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetArchitectureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Architecture, true
}

// SetArchitecture sets field value
func (o *SystemInfoRuntime) SetArchitecture(v string) {
	o.Architecture = v
}

// GetPlatform returns the Platform field value
func (o *SystemInfoRuntime) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *SystemInfoRuntime) SetPlatform(v string) {
	o.Platform = v
}

// GetUname returns the Uname field value
func (o *SystemInfoRuntime) GetUname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uname
}

// GetUnameOk returns a tuple with the Uname field value
// and a boolean to check if the value has been set.
func (o *SystemInfoRuntime) GetUnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uname, true
}

// SetUname sets field value
func (o *SystemInfoRuntime) SetUname(v string) {
	o.Uname = v
}

func (o SystemInfoRuntime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInfoRuntime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["python_version"] = o.PythonVersion
	toSerialize["gunicorn_version"] = o.GunicornVersion
	toSerialize["environment"] = o.Environment
	toSerialize["architecture"] = o.Architecture
	toSerialize["platform"] = o.Platform
	toSerialize["uname"] = o.Uname
	return toSerialize, nil
}

type NullableSystemInfoRuntime struct {
	value *SystemInfoRuntime
	isSet bool
}

func (v NullableSystemInfoRuntime) Get() *SystemInfoRuntime {
	return v.value
}

func (v *NullableSystemInfoRuntime) Set(val *SystemInfoRuntime) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInfoRuntime) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInfoRuntime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInfoRuntime(val *SystemInfoRuntime) *NullableSystemInfoRuntime {
	return &NullableSystemInfoRuntime{value: val, isSet: true}
}

func (v NullableSystemInfoRuntime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInfoRuntime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


