/*
authentik

Making authentication simple.

API version: 2025.2.1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PaginatedSSFStreamList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedSSFStreamList{}

// PaginatedSSFStreamList struct for PaginatedSSFStreamList
type PaginatedSSFStreamList struct {
	Pagination Pagination `json:"pagination"`
	Results []SSFStream `json:"results"`
}

// NewPaginatedSSFStreamList instantiates a new PaginatedSSFStreamList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedSSFStreamList(pagination Pagination, results []SSFStream) *PaginatedSSFStreamList {
	this := PaginatedSSFStreamList{}
	this.Pagination = pagination
	this.Results = results
	return &this
}

// NewPaginatedSSFStreamListWithDefaults instantiates a new PaginatedSSFStreamList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedSSFStreamListWithDefaults() *PaginatedSSFStreamList {
	this := PaginatedSSFStreamList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PaginatedSSFStreamList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedSSFStreamList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedSSFStreamList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetResults returns the Results field value
func (o *PaginatedSSFStreamList) GetResults() []SSFStream {
	if o == nil {
		var ret []SSFStream
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedSSFStreamList) GetResultsOk() ([]SSFStream, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedSSFStreamList) SetResults(v []SSFStream) {
	o.Results = v
}

func (o PaginatedSSFStreamList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedSSFStreamList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullablePaginatedSSFStreamList struct {
	value *PaginatedSSFStreamList
	isSet bool
}

func (v NullablePaginatedSSFStreamList) Get() *PaginatedSSFStreamList {
	return v.value
}

func (v *NullablePaginatedSSFStreamList) Set(val *PaginatedSSFStreamList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedSSFStreamList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedSSFStreamList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedSSFStreamList(val *PaginatedSSFStreamList) *NullablePaginatedSSFStreamList {
	return &NullablePaginatedSSFStreamList{value: val, isSet: true}
}

func (v NullablePaginatedSSFStreamList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedSSFStreamList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


