/*
authentik

Making authentication simple.

API version: 2024.2.1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PatchedExtAuthStageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedExtAuthStageRequest{}

// PatchedExtAuthStageRequest ExtAuthStage Serializer
type PatchedExtAuthStageRequest struct {
	Name *string `json:"name,omitempty"`
	FlowSet []FlowSetRequest `json:"flow_set,omitempty"`
}

// NewPatchedExtAuthStageRequest instantiates a new PatchedExtAuthStageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedExtAuthStageRequest() *PatchedExtAuthStageRequest {
	this := PatchedExtAuthStageRequest{}
	return &this
}

// NewPatchedExtAuthStageRequestWithDefaults instantiates a new PatchedExtAuthStageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedExtAuthStageRequestWithDefaults() *PatchedExtAuthStageRequest {
	this := PatchedExtAuthStageRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedExtAuthStageRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedExtAuthStageRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedExtAuthStageRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedExtAuthStageRequest) SetName(v string) {
	o.Name = &v
}

// GetFlowSet returns the FlowSet field value if set, zero value otherwise.
func (o *PatchedExtAuthStageRequest) GetFlowSet() []FlowSetRequest {
	if o == nil || IsNil(o.FlowSet) {
		var ret []FlowSetRequest
		return ret
	}
	return o.FlowSet
}

// GetFlowSetOk returns a tuple with the FlowSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedExtAuthStageRequest) GetFlowSetOk() ([]FlowSetRequest, bool) {
	if o == nil || IsNil(o.FlowSet) {
		return nil, false
	}
	return o.FlowSet, true
}

// HasFlowSet returns a boolean if a field has been set.
func (o *PatchedExtAuthStageRequest) HasFlowSet() bool {
	if o != nil && !IsNil(o.FlowSet) {
		return true
	}

	return false
}

// SetFlowSet gets a reference to the given []FlowSetRequest and assigns it to the FlowSet field.
func (o *PatchedExtAuthStageRequest) SetFlowSet(v []FlowSetRequest) {
	o.FlowSet = v
}

func (o PatchedExtAuthStageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedExtAuthStageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FlowSet) {
		toSerialize["flow_set"] = o.FlowSet
	}
	return toSerialize, nil
}

type NullablePatchedExtAuthStageRequest struct {
	value *PatchedExtAuthStageRequest
	isSet bool
}

func (v NullablePatchedExtAuthStageRequest) Get() *PatchedExtAuthStageRequest {
	return v.value
}

func (v *NullablePatchedExtAuthStageRequest) Set(val *PatchedExtAuthStageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedExtAuthStageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedExtAuthStageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedExtAuthStageRequest(val *PatchedExtAuthStageRequest) *NullablePatchedExtAuthStageRequest {
	return &NullablePatchedExtAuthStageRequest{value: val, isSet: true}
}

func (v NullablePatchedExtAuthStageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedExtAuthStageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


