/*
authentik

Testing PropertymappingsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_api_PropertymappingsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PropertymappingsApiService PropertymappingsAllDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsAllList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsAllRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsAllTestCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllTestCreate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsAllTypesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllTypesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsAllUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsAllUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsNotificationUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsNotificationUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspacePartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspacePartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderGoogleWorkspaceUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderGoogleWorkspaceUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderMicrosoftEntraUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderMicrosoftEntraUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRacUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRacUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderRadiusUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderRadiusUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderSamlUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderSamlUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScimUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScimUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopePartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopePartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsProviderScopeUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsProviderScopeUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceKerberosUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceKerberosUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceLdapUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceLdapUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceOauthUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceOauthUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourcePlexUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourcePlexUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceSamlUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceSamlUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimDestroy(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimPartialUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimRetrieve(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimUpdate(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertymappingsApiService PropertymappingsSourceScimUsedByList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pmUuid string

		resp, httpRes, err := apiClient.PropertymappingsApi.PropertymappingsSourceScimUsedByList(context.Background(), pmUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
